### ISSUE TITLE
Exporting SRT from NEW does not work

### ISSUE THREAD

**Issue by enzyme69** [jamesruan/SimpleSubtitleEditor#1]
I tried your add on and really like this, I could import SRT fine and edit in in Blender, all good. But exporting SRT when starting from new does not seem to work, maybe I am doing it wrong?

However, I do find that if I have SRT source (even though I do not want this) and erase all the subtitles and export SRT, it seems to work fin.

**Comment by jamesruan** [comment]
Please provide more information. I can't reproduce your problem.

**Comment by jamesruan** [comment]
I think I've known your problem. I'll fix it later

**Comment by enzyme69** [comment]
Thanks a lot James 👍 Yes, apparently if I did "source" some SRT beforehand, even a dummy one, I can generate the SRT export fine.

I am actually using your Subtitle Markers to generate SRT which then I import back using this add-on:
https://github.com/gabrielmontagne/blender-addon-load-subtitles-to-vse

And then I convert it into 3D Text for baking to video.

But VSE Stripes is very powerful, I can use it as "cue" for animation or 3D model generator.

**Comment by enzyme69** [comment]
I have a feeling it is just a matter of typing the correct path into the IO.

Made a tutorial:
https://youtu.be/5EenjsB5-60

**Comment by jamesruan** [comment]
I remove the confusing message bar and exposing exceptions.
I think the incorrect path error is now displayed to user.
@enzyme69  Is your problem solved?
